# Generated by Django 3.0.4 on 2020-03-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_auto_20200319_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
