# Generated by Django 3.0.4 on 2020-03-19 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_book_loanded_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='loanded_out',
            new_name='loaned_out',
        ),
    ]
