# Generated by Django 3.0.4 on 2020-03-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_auto_20200319_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='loaned_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
