# Generated by Django 3.0.4 on 2020-03-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0009_auto_20200320_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='loaner',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
