# Generated by Django 3.0.4 on 2020-03-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0012_auto_20200320_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='loaner',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
