# Generated by Django 3.0.4 on 2020-03-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0015_user_loans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_loans',
            old_name='bookCount',
            new_name='book_count',
        ),
    ]
