# Generated by Django 3.0.4 on 2020-03-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0020_user_access_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Access_Level',
        ),
    ]
